### ISSUE TITLE
无法运行 build.sh 

### ISSUE THREAD

**Issue by zxwsbg** [fumeboy/pome#1]
import的部分配置文件依赖于本地，在项目里未涉及

**Comment by fumeboy** [comment]
抱歉, 我最近会重写这个项目. 这里的 build.sh 实际是要将 pome 程序编译再打包到 docker 镜像中, 但是 .... 

你可以手动编译 pome 程序, 再把编译后的可执行文件移动到 `demo/client/sidecar` 文件夹 和 `demo/server/sidecar` 文件夹下, 之后依照 readme 中的 `编译 & 运行` 部分 就可以了
